package App.Components;

public enum MessageType
{
    CHECKING_IF_PORT_IS_AVAILABLE,
    OK,
    DOES_ID_EXIST,
    DOES_FILE_ID_EXIST,
    FIND_FILE_SUCCESSOR,
    TRANSFER_YOUR_FILES_TO_ME,
    THIS_FILE_BELONGS_TO_YOU,
    NOT_EXIST,
    ALREADY_EXIST,
    FIND_SUCCESSOR,
    GET_YOUR_SUCCESSOR,
    GET_YOUR_PREDECESSOR,
    I_AM_YOUR_NEW_PREDECESSOR,
    I_AM_YOUR_NEW_SUCCESSOR,
    CLOSEST_PRECEDING_FINGER,
    GOT_IT,
    UPDATE_FINGER_TABLE,
    PRINT_YOUR_FINGER_TABLE,
    ARE_YOU_STILL_ALIVE,
    YOU_HAVE_NEW_FILES,
    FIND_FILE,
    IS_FILE_AVAILABLE,
    FILE_IS_AVAILABLE,
    FILE_NOT_AVAILABLE,
    DOWNLOAD_FILE,
    GIVE_YOUR_SHARED_FILES,
    REMOVE_SHARED_FILE
}
